-- Term Selection
select STVTERM_CODE AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_START_DATE > SYSDATE -500 AND STVTERM_START_DATE < SYSDATE + 360
--and substr(stvterm_code,5,1) in ('1','3','5')
ORDER BY STVTERM_CODE DESC

-- aidy
select STVTERM_CODE AS CODE, TO_CHAR(STVTERM_FA_PROC_YR) AS AIDY
from stvterm where stvterm_code= :selTerm.CODE

-- FAFSA loaded
SELECT  PIDM
        , AIDY, BANNERID, LAST_NAME, FIRST_NAME, MIDDLE_NAME
        , CAMPUS_EMAIL, FAFSA_EMAIL, PERS_EMAIL
        , CASE WHEN CELLPHONE IS NULL THEN ''
               WHEN LENGTH(CELLPHONE)=10 THEN CELLPHONE
               ELSE '' END AS PHONE
        ,'LOADED' AS RPT
FROM
(SELECT :selAIDY.AIDY AS AIDY,
       SPRIDEN_PIDM AS PIDM,
       SPRIDEN_ID AS BANNERID,
       CASE WHEN RORSTAT_APPL_RCVD_DATE IS NULL THEN 'NO' ELSE 'YES' END AS FAFSA_FILED,
       SPRIDEN_LAST_NAME AS LAST_NAME,
       SPRIDEN_FIRST_NAME AS FIRST_NAME,
       SPRIDEN_MI AS MIDDLE_NAME,
       SPBPERS_PREF_FIRST_NAME AS PREF_NAME,
       CASE WHEN su.goremal_pidm is not null THEN su.goremal_email_address ELSE '' END as campus_email,
       f.RCRAPP4_EMAIL_ADDRESS AS FAFSA_EMAIL,
       CASE WHEN pers.goremal_pidm is not null THEN pers.goremal_email_address ELSE '' END as pers_email,

       REPLACE(CONCAT(SPRTELE_PHONE_AREA,SPRTELE_PHONE_NUMBER),'-') AS CELLPHONE

       FROM RORSTAT fa
INNER JOIN SPRIDEN ON (fa.rorstat_pidm=SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL)
INNER JOIN SPBPERS ON (SPRIDEN_PIDM=SPBPERS_PIDM)
LEFT OUTER JOIN SPRTELE ON (SPRIDEN_PIDM=SPRTELE_PIDM AND SPRTELE_TELE_CODE IN ('PC','AC') AND SPRTELE_STATUS_IND IS NULL AND SPRTELE_SURROGATE_ID = (SELECT Max(pc2.SPRTELE_SURROGATE_ID) AS MAXID FROM SPRTELE pc2 where SPRIDEN_PIDM=pc2.SPRTELE_PIDM AND pc2.SPRTELE_TELE_CODE IN ('PC','AC') AND pc2.SPRTELE_STATUS_IND IS NULL))
LEFT OUTER JOIN RNVAND0 on (fa.rorstat_pidm=rnvand0_pidm and rnvand0_aidy_code=:selAIDY.AIDY)
left outer JOIN RCRAPP4 f ON (RNVAND0_PIDM=f.RCRAPP4_PIDM AND RNVAND0_AIDY_CODE=f.RCRAPP4_AIDY_CODE and f.RCRAPP4_INFC_CODE='EDE' and f.RCRAPP4_SEQ_NO= (SELECT MAX(f2.RCRAPP4_SEQ_NO) AS MAXSEQ FROM RCRAPP4 f2 where RNVAND0_PIDM=f2.RCRAPP4_PIDM AND RNVAND0_AIDY_CODE=f2.RCRAPP4_AIDY_CODE and f2.RCRAPP4_INFC_CODE='EDE')) --AND RCRAPP4_CURR_REC_IND='Y')
LEFT OUTER JOIN GOREMAL pers ON (SPRIDEN_PIDM=pers.GOREMAL_PIDM and pers.GOREMAL_EMAL_CODE='PERS' and pers.GOREMAL_STATUS_IND='A' AND pers.GOREMAL_SURROGATE_ID=(SELECT MAX(mp.GOREMAL_SURROGATE_ID) AS MAXID FROM GOREMAL mp where SPRIDEN_PIDM=mp.GOREMAL_PIDM and mp.GOREMAL_EMAL_CODE='PERS' and mp.GOREMAL_STATUS_IND='A'))
LEFT OUTER JOIN GOREMAL su ON (SPRIDEN_PIDM=su.GOREMAL_PIDM and su.GOREMAL_EMAL_CODE='SU' and su.GOREMAL_STATUS_IND='A')
WHERE fa.rorstat_aidy_code=:selAIDY.AIDY
AND fa.RORSTAT_APPL_RCVD_DATE is not null
)
ORDER BY RPT, LAST_NAME, FIRST_NAME, BANNERID

-- FAFSA no appl
SELECT PIDM, AIDY, BANNERID, LAST_NAME, FIRST_NAME, MIDDLE_NAME
,CASE  WHEN PHONE IS NULL THEN ''
       WHEN LENGTH(PHONE)=10 THEN PHONE
       ELSE '' END AS PHONE
,CAMPUS_EMAIL
,FAFSA_EMAIL
,PERS_EMAIL
,'NOAPPL' AS RPT
FROM
(select ROTIDEN_PIDM AS PIDM,
       :selAIDY.AIDY AS AIDY
       ,ROTIDEN_ID AS BANNERID
       , ROTIDEN_LAST_NAME AS LAST_NAME, ROTIDEN_FIRST_NAME AS FIRST_NAME, ROTIDEN_MI AS MIDDLE_NAME
       ,REPLACE(CONCAT(ROTADDR_PHONE_AREA,ROTADDR_PHONE_NUMBER),'-') AS PHONE
       ,'' AS CAMPUS_EMAIL
       ,ROTEMAL_EMAIL_ADDRESS AS FAFSA_EMAIL
       ,'' AS PERS_EMAIL
from ROTIDEN
LEFT OUTER JOIN ROTEMAL ON (ROTIDEN_PIDM=ROTEMAL_PIDM AND ROTEMAL_EMAL_CODE='SU')
LEFT OUTER JOIN ROTADDR ON (ROTIDEN_PIDM=ROTADDR_PIDM)
WHERE ROTIDEN_AIDY_CODE=:selAIDY.AIDY
and ROTIDEN_INFC_CODE='EDE'
and ROTIDEN_PIDM IN (SELECT MAX(i.ROTIDEN_PIDM) AS MAXPIDM FROM ROTIDEN i LEFT OUTER JOIN ROTPERS p on (i.ROTIDEN_PIDM=p.ROTPERS_PIDM) where i.ROTIDEN_AIDY_CODE=:selAIDY.AIDY AND i.ROTIDEN_INFC_CODE='EDE' GROUP BY p.ROTPERS_SSN)
)
ORDER BY LAST_NAME, FIRST_NAME, BANNERID