-- aidy selection
select DISTINCT RPRAWRD_AIDY_CODE AS CODE FROM RPRAWRD
ORDER BY RPRAWRD_AIDY_CODE DESC

-- min term (RS)
select STVTERM_CODE AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_CODE >= '202010' AND STVTERM_START_DATE < SYSDATE + 180
and substr(stvterm_code,5,1) in ('1')
ORDER BY STVTERM_CODE DESC

-- min term (general)
select STVTERM_CODE AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_CODE >= '202010' AND STVTERM_START_DATE < SYSDATE + 180
--and substr(stvterm_code,5,1) in ('2','4')
ORDER BY STVTERM_CODE DESC

-- max term
select STVTERM_CODE AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_CODE >= '202010' AND STVTERM_START_DATE < SYSDATE + 360
and substr(stvterm_code,5,1) in ('4','5')
ORDER BY STVTERM_CODE DESC

-- validation
SELECT SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME, RPRAWRD.*
FROM RPRAWRD
INNER JOIN SPRIDEN ON (RPRAWRD_PIDM=SPRIDEN_PIDM and SPRIDEN_CHANGE_IND IS NULL)
WHERE SPRIDEN_ID = :selList.BANNERID
AND RPRAWRD_AIDY_CODE= :selAIDY.CODE

-- uid validation
SELECT * FROM (
SELECT SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME,
CONCAT(CONCAT(RFRFCAT_FCAT_CODE,'_'),RPRAWRD_FUND_CODE) AS GRPIT,
RPRAWRD_PAID_AMT AS SUMIT
FROM RFRFCAT
INNER JOIN RPRAWRD ON (RFRFCAT_FUND_CODE=RPRAWRD_FUND_CODE)

INNER JOIN SPRIDEN ON (RPRAWRD_PIDM=SPRIDEN_PIDM and SPRIDEN_CHANGE_IND IS NULL)
WHERE SPRIDEN_ID = :selList.BANNERID
AND RPRAWRD_AIDY_CODE= :selAIDY.CODE
AND RPRAWRD_PAID_AMT <> 0
)
PIVOT
(
SUM(SUMIT)
FOR GRPIT
IN (
'ENDOW_AAS' ENDOW_AAS,
'ENDOW_ACS' ENDOW_ACS,
'ENDOW_ADS'	ENDOW_ADS,
'ENDOW_AKS'	ENDOW_AKS,
'ENDOW_ALM'	ENDOW_ALM,
'ENDOW_ANE'	ENDOW_ANE,
'ENDOW_ARV'	ENDOW_ARV,
'ENDOW_ATS'	ENDOW_ATS,
'ENDOW_AVS'	ENDOW_AVS,
'ENDOW_BAR'	ENDOW_BAR,
'ENDOW_BAS'	ENDOW_BAS,
'ENDOW_BAX'	ENDOW_BAX,
'ENDOW_BFS'	ENDOW_BFS,
'ENDOW_BKL'	ENDOW_BKL,
'ENDOW_BMM'	ENDOW_BMM,
'ENDOW_BRG'	ENDOW_BRG,
'ENDOW_BRN'	ENDOW_BRN,
'ENDOW_BRT'	ENDOW_BRT,
'ENDOW_BSA'	ENDOW_BSA,
'ENDOW_BSS'	ENDOW_BSS,
'ENDOW_BTT'	ENDOW_BTT,
'ENDOW_BUH'	ENDOW_BUH,
'ENDOW_BUR'	ENDOW_BUR,
'ENDOW_BWS'	ENDOW_BWS,
'ENDOW_C31'	ENDOW_C31,
'ENDOW_C39'	ENDOW_C39,
'ENDOW_C43'	ENDOW_C43,
'ENDOW_C51'	ENDOW_C51,
'ENDOW_C56'	ENDOW_C56,
'ENDOW_C57'	ENDOW_C57,
'ENDOW_C58'	ENDOW_C58,
'ENDOW_C59'	ENDOW_C59,
'ENDOW_C64'	ENDOW_C64,
'ENDOW_C68'	ENDOW_C68,
'ENDOW_CAS'	ENDOW_CAS,
'ENDOW_CBS'	ENDOW_CBS,
'ENDOW_CCB'	ENDOW_CCB,
'ENDOW_CFC'	ENDOW_CFC,
'ENDOW_CHE'	ENDOW_CHE,
'ENDOW_CHF'	ENDOW_CHF,
'ENDOW_CHU'	ENDOW_CHU,
'ENDOW_CJD'	ENDOW_CJD,
'ENDOW_CLB'	ENDOW_CLB,
'ENDOW_CLI'	ENDOW_CLI,
'ENDOW_CLP'	ENDOW_CLP,
'ENDOW_CLR'	ENDOW_CLR,
'ENDOW_CMH'	ENDOW_CMH,
'ENDOW_COL'	ENDOW_COL,
'ENDOW_COT'	ENDOW_COT,
'ENDOW_COX'	ENDOW_COX,
'ENDOW_CRM'	ENDOW_CRM,
'ENDOW_CRS'	ENDOW_CRS,
'ENDOW_CSA'	ENDOW_CSA,
'ENDOW_DCS'	ENDOW_DCS,
'ENDOW_DCW'	ENDOW_DCW,
'ENDOW_DDF'	ENDOW_DDF,
'ENDOW_DEN'	ENDOW_DEN,
'ENDOW_DMC'	ENDOW_DMC,
'ENDOW_DOR'	ENDOW_DOR,
'ENDOW_DUB'	ENDOW_DUF,
'ENDOW_ECK'	ENDOW_ECK,
'ENDOW_EDF'	ENDOW_EDF,
'ENDOW_ERE'	ENDOW_ERE,
'ENDOW_ESK'	ENDOW_ESK,
'ENDOW_FAR'	ENDOW_FAR,
'ENDOW_FCF'	ENDOW_FCF,
'ENDOW_FCS'	ENDOW_FCS,
'ENDOW_FDF'	ENDOW_FDF,
'ENDOW_FEF'	ENDOW_FEF,
'ENDOW_FES'	ENDOW_FES,
'ENDOW_FOR'	ENDOW_FOR,
'ENDOW_FRI'	ENDOW_FRI,
'ENDOW_FSF'	ENDOW_FSF,
'ENDOW_GBM'	ENDOW_GBM,
'ENDOW_GFE'	ENDOW_GFE,
'ENDOW_GFM'	ENDOW_GFM,
'ENDOW_GKB'	ENDOW_GKB,
'ENDOW_GLS'	ENDOW_GLS,
'ENDOW_GSB'	ENDOW_GSB,
'ENDOW_GUT'	ENDOW_GUT,
'ENDOW_GUZ'	ENDOW_GUZ,
'ENDOW_GWC'	ENDOW_GWC,
'ENDOW_GWL'	ENDOW_GWL,
'ENDOW_HAM'	ENDOW_HAM,
'ENDOW_HHP'	ENDOW_HHP,
'ENDOW_HIC'	ENDOW_HIC,
'ENDOW_HJM'	ENDOW_HJM,
'ENDOW_HPB'	ENDOW_HPB,
'ENDOW_HRS'	ENDOW_HRS,
'ENDOW_HSC'	ENDOW_HSC,
'ENDOW_HUP'	ENDOW_HUP,
'ENDOW_HUT'	ENDOW_HUT,
'ENDOW_IPT'	ENDOW_IPT,
'ENDOW_ITS'	ENDOW_ITS,
'ENDOW_JAH'	ENDOW_JAH,
'ENDOW_JBP'	ENDOW_JBP,
'ENDOW_JCM'	ENDOW_JCM,
'ENDOW_JDS'	ENDOW_JDS,
'ENDOW_JEG'	ENDOW_JEG,
'ENDOW_JFS'	ENDOW_JFS,
'ENDOW_JJM'	ENDOW_JJM,
'ENDOW_JMC'	ENDOW_JMC,
'ENDOW_JOB'	ENDOW_JOB,
'ENDOW_JOF'	ENDOW_JOF,
'ENDOW_JPC'	ENDOW_JPC,
'ENDOW_JRH'	ENDOW_JRH,
'ENDOW_KBS'	ENDOW_KBS,
'ENDOW_KER'	ENDOW_KER,
'ENDOW_KET'	ENDOW_KET,
'ENDOW_KOM'	ENDOW_KOM,
'ENDOW_KPD'	ENDOW_KPD,
'ENDOW_LAC'	ENDOW_LAC,
'ENDOW_LAF'	ENDOW_LAF,
'ENDOW_LAG'	ENDOW_LAG,
'ENDOW_LAN'	ENDOW_LAN,
'ENDOW_LEA'	ENDOW_LEA,
'ENDOW_LJS'	ENDOW_LJS,
'ENDOW_LMC'	ENDOW_LMC,
'ENDOW_LSA'	ENDOW_LSA,
'ENDOW_LSF'	ENDOW_LSF,
'ENDOW_LWX'	ENDOW_LWX,
'ENDOW_LYN'	ENDOW_LYN,
'ENDOW_MAC'	ENDOW_MAC,
'ENDOW_MCK'	ENDOW_MCK,
'ENDOW_MES'	ENDOW_MES,
'ENDOW_MFF'	ENDOW_MFF,
'ENDOW_MOR'	ENDOW_MOR,
'ENDOW_MRC'	ENDOW_MRC,
'ENDOW_MSF'	ENDOW_MSF,
'ENDOW_MWS'	ENDOW_MWS,
'ENDOW_MYP'	ENDOW_MYP,
'ENDOW_MYR'	ENDOW_MYR,
'ENDOW_NAE'	ENDOW_NAE,
'ENDOW_NMY'	ENDOW_NMY,
'ENDOW_NYF'	ENDOW_NYF,
'ENDOW_OBG'	ENDOW_OBG,
'ENDOW_PAP'	ENDOW_PAP,
'ENDOW_PCS'	ENDOW_PCS,
'ENDOW_PJL'	ENDOW_PJL,
'ENDOW_PND'	ENDOW_PND,
'ENDOW_PPI'	ENDOW_PPI,
'ENDOW_PVW'	ENDOW_PVW,
'ENDOW_PWR'	ENDOW_PWR,
'ENDOW_R61'	ENDOW_R61,
'ENDOW_RBJ'	ENDOW_RBJ,
'ENDOW_RCH'	ENDOW_RCH,
'ENDOW_RGP'	ENDOW_RGP,
'ENDOW_RGR'	ENDOW_RGR,
'ENDOW_RIZ'	ENDOW_RIZ,
'ENDOW_RJS'	ENDOW_RJS,
'ENDOW_RLP'	ENDOW_RLP,
'ENDOW_ROB'	ENDOW_ROB,
'ENDOW_RRO'	ENDOW_RRO,
'ENDOW_RRS'	ENDOW_RRS,
'ENDOW_RSE'	ENDOW_RSE,
'ENDOW_RSK'	ENDOW_RSK,
'ENDOW_RSW'	ENDOW_RSW,
'ENDOW_RVH'	ENDOW_RVH,
'ENDOW_RWW'	ENDOW_RWW,
'ENDOW_RZM'	ENDOW_RZM,
'ENDOW_SAM'	ENDOW_SAM,
'ENDOW_SAT'	ENDOW_SAT,
'ENDOW_SCT'	ENDOW_SCT,
'ENDOW_SCU'	ENDOW_SCU,
'ENDOW_SGA'	ENDOW_SGA,
'ENDOW_SGT'	ENDOW_SGT,
'ENDOW_SIM'	ENDOW_SIM,
'ENDOW_SIS'	ENDOW_SIS,
'ENDOW_SMS'	ENDOW_SMS,
'ENDOW_SON'	ENDOW_SON,
'ENDOW_SPA'	ENDOW_SPA,
'ENDOW_SRC'	ENDOW_SRC,
'ENDOW_SRT'	ENDOW_SRT,
'ENDOW_SSF'	ENDOW_SSF,
'ENDOW_SSM'	ENDOW_SSM,
'ENDOW_STG'	ENDOW_STG,
'ENDOW_SUS'	ENDOW_SUS,
'ENDOW_SUT'	ENDOW_SUT,
'ENDOW_SZW'	ENDOW_SZW,
'ENDOW_TBX'	ENDOW_TBX,
'ENDOW_TRF'	ENDOW_TRF,
'ENDOW_TSF'	ENDOW_TSF,
'ENDOW_TZS'	ENDOW_TZS,
'ENDOW_ULA'	ENDOW_ULA,
'ENDOW_VEW'	ENDOW_VEW,
'ENDOW_WEA'	ENDOW_WEA,
'ENDOW_WET'	ENDOW_WET,
'ENDOW_WID'	ENDOW_WID,
'ENDOW_WMJ'	ENDOW_WMJ,
'ENDOW_WMK'	ENDOW_WMK,
'ENDOW_WOL'	ENDOW_WOL,
'ENDOW_WSM'	ENDOW_WSM,
'ENDOW_WSS'	ENDOW_WSS,
'ENDOW_ZAB'	ENDOW_ZAB,
'ESF_AEG'	ESF_AEG,
'ESF_ASI'	ESF_ASI,
'ESF_BTS'	ESF_BTS,
'ESF_CAG'	ESF_CAG,
'ESF_CHA'	ESF_CHA,
'ESF_ESF'	ESF_ESF,
'ESF_GBF'	ESF_GBF,
'ESF_GDA'	ESF_GDA,
'ESF_INT'	ESF_INT,
'ESF_LEG'	ESF_LEG,
'ESF_NSF'	ESF_NSF,
'ESF_NTS'	ESF_NTS,
'ESF_OCC'	ESF_OCC,
'ESF_PSA'	ESF_PSA,
'ESF_PTK'	ESF_PTK,
'ESF_REN'	ESF_REN,
'ESF_RMS'	ESF_RMS,
'ESF_SFA'	ESF_SFA,
'ESF_STC'	ESF_STC,
'ESF_TRN'	ESF_TRN,
'FED_FGPLS'	FED_FGPLS,
'FED_FPELL'	FED_FPELL,
'FED_FPLS'	FED_FPLS,
'FED_FSEOG'	FED_FSEOG,
'FED_FSUB'	FED_FSUB,
'FED_FUSB'	FED_FUSB,
'GRAD_GTSRD'	GRAD_GTSRD,
'GRAD_GTSRP'	GRAD_GTSRP,
'GRAD_GTSSD'	GRAD_GTSSD,
'GRAD_GTSSP'	GRAD_GTSSP,
'HESC_CVT'	HESC_CVT,
'HESC_EXC'	HESC_EXC,
'HESC_EXS'	HESC_EXS,
'HESC_MSR'	HESC_MSR,
'HESC_NYA'	HESC_NYA,
'HESC_NYH'	HESC_NYH,
'HESC_NYS'	HESC_NYS,
'HESC_PTT'	HESC_PTT,
'HESC_TAE'	HESC_TAE,
'HESC_TAP'	HESC_TAP,
'HESC_TAS'	HESC_TAS,
'HESC_VTA'	HESC_VTA,
'HESC_WTC'	HESC_WTC,
'NYS_DAS'	NYS_DAS,
'NYS_EOP'	NYS_EOP,
'NYS_ESD'	NYS_ESD,
'NYS_FYF'	NYS_FYF,
'NYS_GDF'	NYS_GDF,
'NYS_INA'	NYS_INA,
'NYS_SIG'	NYS_SIG,
'NYS_STA'	NYS_STA,
'SPPF_BPM'	SPPF_BPM,
'SPPF_DEC'	SPPF_DEC,
'SPPF_GAO'	SPPF_GAO,
'SPPF_GSC'	SPPF_GSC,
'SPPF_HTZ'	SPPF_HTZ,
'SPPF_KDR'	SPPF_KDR,
'SPPF_RMA'	SPPF_RMA,
'SPPF_SCA'	SPPF_SCA,
'SPPF_SPP'	SPPF_SPP)
)

-- stdn reg verification
SELECT SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME, sgbstdn.*
FROM SGBSTDN
INNER JOIN SPRIDEN ON (SGBSTDN_PIDM=SPRIDEN_PIDM and SPRIDEN_CHANGE_IND IS NULL)
WHERE SPRIDEN_ID = :selList.BANNERID

-- funding
Select * from rfrfcat

-- group funding
--SELECT RFRFCAT_FCAT_CODE, RFRFCAT_FUND_CODE FROM RFRFCAT
select grpcod as grp1, grpcod as grp2 from (
SELECT (CONCAT(CONCAT(RTRIM(RFRFCAT_FCAT_CODE),'_'),RFRFCAT_FUND_CODE)) AS GRPCOD FROM RFRFCAT ORDER BY RFRFCAT_FCAT_CODE, RFRFCAT_FUND_CODE)